language: php

php:
    - 5.3

before_script:
    - php -r "eval('?>'.file_get_contents('https://getcomposer.org/installer'));"
    - php composer.phar install --dev --prefer-source
    - vendor/bin/phpcs --config-set default_standard PSR2

script:
    - vendor/bin/phpcs -n --extensions=php --ignore=*/vendor/*,*/Resources/* .
    - vendor/bin/phpmd  --suffixes php --exclude vendor . text codesize,naming,controversial,design
    - vendor/bin/phpunit
