language: php

php:
    - 5.3
    - 5.4

before_script:
    - composer install --dev --prefer-source
    - vendor/bin/phpcs --config-set default_standard PSR2

script:
    - vendor/bin/phpcs -n --extensions=php --ignore=*/vendor/* .
